// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/thing.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ThingIn struct {
	Field                string   `protobuf:"bytes,1,opt,name=Field,json=field,proto3" json:"Field,omitempty"`
	URL                  string   `protobuf:"bytes,2,opt,name=URL,json=url,proto3" json:"URL,omitempty"`
	Number               int64    `protobuf:"varint,3,opt,name=Number,json=number,proto3" json:"Number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThingIn) Reset()         { *m = ThingIn{} }
func (m *ThingIn) String() string { return proto.CompactTextString(m) }
func (*ThingIn) ProtoMessage()    {}
func (*ThingIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba090fff2d0f56b8, []int{0}
}

func (m *ThingIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThingIn.Unmarshal(m, b)
}
func (m *ThingIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThingIn.Marshal(b, m, deterministic)
}
func (m *ThingIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThingIn.Merge(m, src)
}
func (m *ThingIn) XXX_Size() int {
	return xxx_messageInfo_ThingIn.Size(m)
}
func (m *ThingIn) XXX_DiscardUnknown() {
	xxx_messageInfo_ThingIn.DiscardUnknown(m)
}

var xxx_messageInfo_ThingIn proto.InternalMessageInfo

func (m *ThingIn) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *ThingIn) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *ThingIn) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type ThingOut struct {
	Field                string   `protobuf:"bytes,1,opt,name=Field,json=field,proto3" json:"Field,omitempty"`
	URL                  string   `protobuf:"bytes,2,opt,name=URL,json=url,proto3" json:"URL,omitempty"`
	Number               int64    `protobuf:"varint,3,opt,name=Number,json=number,proto3" json:"Number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThingOut) Reset()         { *m = ThingOut{} }
func (m *ThingOut) String() string { return proto.CompactTextString(m) }
func (*ThingOut) ProtoMessage()    {}
func (*ThingOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba090fff2d0f56b8, []int{1}
}

func (m *ThingOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThingOut.Unmarshal(m, b)
}
func (m *ThingOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThingOut.Marshal(b, m, deterministic)
}
func (m *ThingOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThingOut.Merge(m, src)
}
func (m *ThingOut) XXX_Size() int {
	return xxx_messageInfo_ThingOut.Size(m)
}
func (m *ThingOut) XXX_DiscardUnknown() {
	xxx_messageInfo_ThingOut.DiscardUnknown(m)
}

var xxx_messageInfo_ThingOut proto.InternalMessageInfo

func (m *ThingOut) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *ThingOut) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *ThingOut) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func init() {
	proto.RegisterType((*ThingIn)(nil), "protos.ThingIn")
	proto.RegisterType((*ThingOut)(nil), "protos.ThingOut")
}

func init() { proto.RegisterFile("protos/thing.proto", fileDescriptor_ba090fff2d0f56b8) }

var fileDescriptor_ba090fff2d0f56b8 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x2f, 0xc9, 0xc8, 0xcc, 0x4b, 0xd7, 0x03, 0x73, 0x84, 0xd8, 0x20, 0x62, 0x4a,
	0x9e, 0x5c, 0xec, 0x21, 0x20, 0x61, 0xcf, 0x3c, 0x21, 0x11, 0x2e, 0x56, 0xb7, 0xcc, 0xd4, 0x9c,
	0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0xd6, 0x34, 0x10, 0x47, 0x48, 0x80, 0x8b, 0x39,
	0x34, 0xc8, 0x47, 0x82, 0x09, 0x2c, 0xc6, 0x5c, 0x5a, 0x94, 0x23, 0x24, 0xc6, 0xc5, 0xe6, 0x57,
	0x9a, 0x9b, 0x94, 0x5a, 0x24, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x1c, 0xc4, 0x96, 0x07, 0xe6, 0x29,
	0x79, 0x71, 0x71, 0x80, 0x8d, 0xf2, 0x2f, 0x2d, 0xa1, 0xd4, 0x2c, 0x23, 0x47, 0x2e, 0x1e, 0xb0,
	0x59, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x86, 0x5c, 0x3c, 0x01, 0x45, 0xf9, 0xc9,
	0xa9, 0xc5, 0xc5, 0x60, 0x61, 0x21, 0x7e, 0x88, 0x37, 0x8a, 0xf5, 0xa0, 0x8e, 0x97, 0x12, 0x40,
	0x11, 0xf0, 0x2f, 0x2d, 0x71, 0xe2, 0x8a, 0xe2, 0xd0, 0xb3, 0x86, 0x08, 0x26, 0x41, 0x7c, 0x6b,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x37, 0x5f, 0x0c, 0x0a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ThingRequestClient is the client API for ThingRequest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ThingRequestClient interface {
	ProcessThing(ctx context.Context, in *ThingIn, opts ...grpc.CallOption) (*ThingOut, error)
}

type thingRequestClient struct {
	cc *grpc.ClientConn
}

func NewThingRequestClient(cc *grpc.ClientConn) ThingRequestClient {
	return &thingRequestClient{cc}
}

func (c *thingRequestClient) ProcessThing(ctx context.Context, in *ThingIn, opts ...grpc.CallOption) (*ThingOut, error) {
	out := new(ThingOut)
	err := c.cc.Invoke(ctx, "/protos.ThingRequest/ProcessThing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThingRequestServer is the server API for ThingRequest service.
type ThingRequestServer interface {
	ProcessThing(context.Context, *ThingIn) (*ThingOut, error)
}

// UnimplementedThingRequestServer can be embedded to have forward compatible implementations.
type UnimplementedThingRequestServer struct {
}

func (*UnimplementedThingRequestServer) ProcessThing(ctx context.Context, req *ThingIn) (*ThingOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessThing not implemented")
}

func RegisterThingRequestServer(s *grpc.Server, srv ThingRequestServer) {
	s.RegisterService(&_ThingRequest_serviceDesc, srv)
}

func _ThingRequest_ProcessThing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThingIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThingRequestServer).ProcessThing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ThingRequest/ProcessThing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThingRequestServer).ProcessThing(ctx, req.(*ThingIn))
	}
	return interceptor(ctx, in, info, handler)
}

var _ThingRequest_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.ThingRequest",
	HandlerType: (*ThingRequestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessThing",
			Handler:    _ThingRequest_ProcessThing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/thing.proto",
}
